# .github/workflows/main.yml
on:
  push:
    branches:
      - main
      - master

jobs:
  post_tweet_job:
    runs-on: ubuntu-latest
    name: Post tweet to Twitter
    steps:
    - name: Tweets link to every commit
      uses: sw-yx/github-to-tweet-v2@main
      with:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
